extern const GeoLayout blue_coin_geo[];
extern Lights1 blue_coin_f3dlite_material_004_lights;
extern Lights1 blue_coin_f3dlite_material_003_lights;
extern Vtx blue_coin_000_displaylist_mesh_layer_1_vtx_0[100];
extern Gfx blue_coin_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx blue_coin_000_displaylist_mesh_layer_1_vtx_1[114];
extern Gfx blue_coin_000_displaylist_mesh_layer_1_tri_1[];
extern Gfx mat_blue_coin_f3dlite_material_004[];
extern Gfx mat_revert_blue_coin_f3dlite_material_004[];
extern Gfx mat_blue_coin_f3dlite_material_003[];
extern Gfx mat_revert_blue_coin_f3dlite_material_003[];
extern Gfx blue_coin_000_displaylist_mesh_layer_1[];
