extern const GeoLayout vcutm_area_1_geo[];
extern const GeoLayout vcutm_area_1[];
extern const Collision vcutm_area_1_collision[];
extern const MacroObject vcutm_area_1_macro_objs[];
extern Lights1 vcutm_dl_Death_Plane_lights;
extern Lights1 vcutm_dl_Brown_Walls_None_Culling_lights;
extern u8 vcutm_dl_bbh_textures_09000_rgba16_ci8[];
extern u8 vcutm_dl_bbh_textures_09000_rgba16_pal_rgba16[];
extern Vtx vcutm_dl_Death_Plane_mesh_layer_1_vtx_0[4];
extern Gfx vcutm_dl_Death_Plane_mesh_layer_1_tri_0[];
extern Vtx vcutm_dl_Plane_mesh_layer_1_vtx_0[96];
extern Gfx vcutm_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx vcutm_dl_Plane_001_mesh_layer_1_vtx_0[24];
extern Gfx vcutm_dl_Plane_001_mesh_layer_1_tri_0[];
extern Vtx vcutm_dl_Plane_002_mesh_layer_1_vtx_0[72];
extern Gfx vcutm_dl_Plane_002_mesh_layer_1_tri_0[];
extern Gfx mat_vcutm_dl_Death_Plane[];
extern Gfx mat_revert_vcutm_dl_Death_Plane[];
extern Gfx mat_vcutm_dl_Brown_Walls_None_Culling[];
extern Gfx mat_revert_vcutm_dl_Brown_Walls_None_Culling[];
extern Gfx vcutm_dl_Death_Plane_mesh_layer_1[];
extern Gfx vcutm_dl_Plane_mesh_layer_1[];
extern Gfx vcutm_dl_Plane_001_mesh_layer_1[];
extern Gfx vcutm_dl_Plane_002_mesh_layer_1[];
