extern const GeoLayout sa_area_1_geo[];
extern const GeoLayout sa_dl_Room2_geo[];
extern const GeoLayout sa_dl_Room3_geo[];
extern const GeoLayout sa_area_1[];
extern const Collision sa_area_1_collision[];
extern const u8 sa_area_1_collision_rooms[];
extern const MacroObject sa_area_1_macro_objs[];
extern Lights1 sa_dl_f3dlite_material_lights;
extern Vtx sa_dl_Plane_001_mesh_layer_1_vtx_0[4];
extern Gfx sa_dl_Plane_001_mesh_layer_1_tri_0[];
extern Gfx mat_sa_dl_f3dlite_material[];
extern Gfx mat_revert_sa_dl_f3dlite_material[];
extern Gfx sa_dl_Plane_001_mesh_layer_1[];
