extern const GeoLayout pizza_geo[];
extern Lights1 pizza_Crust_lights;
extern Lights1 pizza_Main_Pizza_lights;
extern u8 pizza_Pizza_rgba16[];
extern Vtx pizza_000_offset_mesh_layer_1_vtx_0[64];
extern Gfx pizza_000_offset_mesh_layer_1_tri_0[];
extern Vtx pizza_000_offset_mesh_layer_5_vtx_0[27];
extern Gfx pizza_000_offset_mesh_layer_5_tri_0[];
extern Gfx mat_pizza_Crust[];
extern Gfx mat_revert_pizza_Crust[];
extern Gfx mat_pizza_Main_Pizza[];
extern Gfx mat_revert_pizza_Main_Pizza[];
extern Gfx pizza_000_offset_mesh_layer_1[];
extern Gfx pizza_000_offset_mesh_layer_5[];
