extern const GeoLayout yellow_coin_geo[];
extern Lights1 yellow_coin_f3dlite_material_lights;
extern Lights1 yellow_coin_f3dlite_material_002_lights;
extern Vtx yellow_coin_000_displaylist_mesh_layer_1_vtx_0[100];
extern Gfx yellow_coin_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx yellow_coin_000_displaylist_mesh_layer_1_vtx_1[114];
extern Gfx yellow_coin_000_displaylist_mesh_layer_1_tri_1[];
extern Gfx mat_yellow_coin_f3dlite_material[];
extern Gfx mat_revert_yellow_coin_f3dlite_material[];
extern Gfx mat_yellow_coin_f3dlite_material_002[];
extern Gfx mat_revert_yellow_coin_f3dlite_material_002[];
extern Gfx yellow_coin_000_displaylist_mesh_layer_1[];
